namespace Utility.Enum
{
    public enum SitePageType
    {
        Home = 1,
        AboutUs = 2,
        Attraction = 3,
        Activity = 4,
        Projects = 5,
        News = 6,
        Events = 7,
        MediaGallery = 8,
        Careers = 9,
        GetInTouch = 10,
        QuickLinks = 11,
        InformationRequest = 12,
        GrievanceForm = 13,
        RightToAccessInformation = 14,
        TermsAndConditions = 15,
        PrivacyPolicy = 16,
        KuwaitTowers = 17,
        Clubs = 18,
        Resorts = 19,
        Beaches = 20,
        ParksGardens = 21,
        Entertainment = 22,
        Swimming = 23,
        HealthFitness = 24,
        KidsPlayAreas = 25,
        ThemeParks = 26,
        RentChalets = 27,
        ActivityBeaches = 28,
        BoatsYachts = 29,
        PicnicSpots = 30,
        Dining = 31,
        Festivals = 32,
        ActivityEntertainment = 33,
        PanoramicView = 34,
        TermsCondition = 35,
        ContactUs = 36,
        AttractionType = 37,
        SiteMenu = 38,
        ActivityType = 39,
        Faisal=40,
        FaisalType=41,
        Category=42
    }
}
