//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResourceEn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResourceEn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("API.Resources.SharedResourceEn", typeof(SharedResourceEn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A request has been received to change the password for your account registered with email address.
        /// </summary>
        public static string a_request_has_been_received_to_change_the_password_for_your_account_registered_with_email_address {
            get {
                return ResourceManager.GetString("a_request_has_been_received_to_change_the_password_for_your_account_registered_wi" +
                        "th_email_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string about_us {
            get {
                return ResourceManager.GetString("about_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket already generated.
        /// </summary>
        public static string already_ticket_generated {
            get {
                return ResourceManager.GetString("already_ticket_generated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Name Already Exists.
        /// </summary>
        public static string area_name_already_exists {
            get {
                return ResourceManager.GetString("area_name_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        public static string at {
            get {
                return ResourceManager.GetString("at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad.
        /// </summary>
        public static string bad {
            get {
                return ResourceManager.GetString("bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string cancelled {
            get {
                return ResourceManager.GetString("cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civil ID is already registered.
        /// </summary>
        public static string civil_id_is_already_registered {
            get {
                return ResourceManager.GetString("civil_id_is_already_registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Added Successfully.
        /// </summary>
        public static string company_added_successfully {
            get {
                return ResourceManager.GetString("company_added_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name Already Exists.
        /// </summary>
        public static string company_name_already_exists {
            get {
                return ResourceManager.GetString("company_name_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company publish limit is reached.
        /// </summary>
        public static string company_publish_limit_is_reached {
            get {
                return ResourceManager.GetString("company_publish_limit_is_reached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company upload limit is reached.
        /// </summary>
        public static string company_upload_limit_is_reached {
            get {
                return ResourceManager.GetString("company_upload_limit_is_reached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string completed {
            get {
                return ResourceManager.GetString("completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter name already exists.
        /// </summary>
        public static string counter_name_already_exists {
            get {
                return ResourceManager.GetString("counter_name_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Password.
        /// </summary>
        public static string create_password {
            get {
                return ResourceManager.GetString("create_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently Service is not available..
        /// </summary>
        public static string currently_service_is_not_available {
            get {
                return ResourceManager.GetString("currently_service_is_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist.
        /// </summary>
        public static string customer_not_exists {
            get {
                return ResourceManager.GetString("customer_not_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} Days Remaining).
        /// </summary>
        public static string days_days_remaining {
            get {
                return ResourceManager.GetString("days_days_remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to department name already exists.
        /// </summary>
        public static string department_name_already_exists {
            get {
                return ResourceManager.GetString("department_name_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Uploaded Successfully.
        /// </summary>
        public static string document_uploaded_successfully {
            get {
                return ResourceManager.GetString("document_uploaded_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email is already taken.
        /// </summary>
        public static string email_is_already_taken {
            get {
                return ResourceManager.GetString("email_is_already_taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered OTP has expired.
        /// </summary>
        public static string entered_otp_has_expired {
            get {
                return ResourceManager.GetString("entered_otp_has_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered OTP is incorrect.
        /// </summary>
        public static string entered_otp_is_incorrect {
            get {
                return ResourceManager.GetString("entered_otp_is_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated waiting time.
        /// </summary>
        public static string estimated_waiting_time {
            get {
                return ResourceManager.GetString("estimated_waiting_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Expired).
        /// </summary>
        public static string expired {
            get {
                return ResourceManager.GetString("expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback submitted!.
        /// </summary>
        public static string feedback_submitted {
            get {
                return ResourceManager.GetString("feedback_submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size exceed 1 MB.
        /// </summary>
        public static string file_size_exceed_1_mb {
            get {
                return ResourceManager.GetString("file_size_exceed_1_mb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Name Exist.
        /// </summary>
        public static string folder_name_exist {
            get {
                return ResourceManager.GetString("folder_name_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message has been submitted. We will get back to you soon..
        /// </summary>
        public static string get_in_touch_submit {
            get {
                return ResourceManager.GetString("get_in_touch_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Governorate Name Already Exists.
        /// </summary>
        public static string governorate_name_already_exists {
            get {
                return ResourceManager.GetString("governorate_name_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great.
        /// </summary>
        public static string great {
            get {
                return ResourceManager.GetString("great", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been registered with SERA. Please set your password using the button below..
        /// </summary>
        public static string has_been_registered_with_sera_please_set_your_password_using_the_button_below {
            get {
                return ResourceManager.GetString("has_been_registered_with_sera_please_set_your_password_using_the_button_below", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        public static string hi {
            get {
                return ResourceManager.GetString("hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold.
        /// </summary>
        public static string hold {
            get {
                return ResourceManager.GetString("hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string hour {
            get {
                return ResourceManager.GetString("hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again later..
        /// </summary>
        public static string http_500_internal_server_error {
            get {
                return ResourceManager.GetString("http_500_internal_server_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive Customer.
        /// </summary>
        public static string inactive_customer {
            get {
                return ResourceManager.GetString("inactive_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again later..
        /// </summary>
        public static string internal_server_error {
            get {
                return ResourceManager.GetString("internal_server_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again later..
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as Read.
        /// </summary>
        public static string mark_as_read {
            get {
                return ResourceManager.GetString("mark_as_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as Unread.
        /// </summary>
        public static string mark_as_unread {
            get {
                return ResourceManager.GetString("mark_as_unread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string minute {
            get {
                return ResourceManager.GetString("minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number is already registered.
        /// </summary>
        public static string mobile_number_is_already_registered {
            get {
                return ResourceManager.GetString("mobile_number_is_already_registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Account Confirmation.
        /// </summary>
        public static string new_account_confirmation {
            get {
                return ResourceManager.GetString("new_account_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New record created successfully.
        /// </summary>
        public static string new_record_created_successfully {
            get {
                return ResourceManager.GetString("new_record_created_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version is available on AppStore please download.
        /// </summary>
        public static string new_version_is_available_on_appstore_please_download {
            get {
                return ResourceManager.GetString("new_version_is_available_on_appstore_please_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version is available on Play Store please download.
        /// </summary>
        public static string new_version_is_available_on_play_store_please_download {
            get {
                return ResourceManager.GetString("new_version_is_available_on_play_store_please_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Companies Available.
        /// </summary>
        public static string no_companies_available {
            get {
                return ResourceManager.GetString("no_companies_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No notifications.
        /// </summary>
        public static string no_notifications {
            get {
                return ResourceManager.GetString("no_notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Services Available.
        /// </summary>
        public static string no_services_available {
            get {
                return ResourceManager.GetString("no_services_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Show.
        /// </summary>
        public static string no_show {
            get {
                return ResourceManager.GetString("no_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tickets.
        /// </summary>
        public static string no_tickets {
            get {
                return ResourceManager.GetString("no_tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Officer Hold.
        /// </summary>
        public static string officer_hold {
            get {
                return ResourceManager.GetString("officer_hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        public static string okay {
            get {
                return ResourceManager.GetString("okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is wrong.
        /// </summary>
        public static string password_is_wrong {
            get {
                return ResourceManager.GetString("password_is_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset.
        /// </summary>
        public static string password_reset {
            get {
                return ResourceManager.GetString("password_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid Folder Name.
        /// </summary>
        public static string please_enter_valid_folder_name {
            get {
                return ResourceManager.GetString("please_enter_valid_folder_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Updated Successfully.
        /// </summary>
        public static string profile_updated_successfully {
            get {
                return ResourceManager.GetString("profile_updated_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconfigure all existing services on adding a new level.
        /// </summary>
        public static string reconfigure_all_existing_services_on_adding_a_new_level {
            get {
                return ResourceManager.GetString("reconfigure_all_existing_services_on_adding_a_new_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string reset_password {
            get {
                return ResourceManager.GetString("reset_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERA Team.
        /// </summary>
        public static string sera_team {
            get {
                return ResourceManager.GetString("sera_team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service limit reached.
        /// </summary>
        public static string service_limit_reached {
            get {
                return ResourceManager.GetString("service_limit_reached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serving Now.
        /// </summary>
        public static string serving_now {
            get {
                return ResourceManager.GetString("serving_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to success.
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You.
        /// </summary>
        public static string thank_you {
            get {
                return ResourceManager.GetString("thank_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket cancelled Successfully.
        /// </summary>
        public static string ticket_cancelled_successfully {
            get {
                return ResourceManager.GetString("ticket_cancelled_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Generated Successfully.
        /// </summary>
        public static string ticket_generated_successfully {
            get {
                return ResourceManager.GetString("ticket_generated_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload limit is reached.
        /// </summary>
        public static string upload_limit_is_reached {
            get {
                return ResourceManager.GetString("upload_limit_is_reached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user created successfully.
        /// </summary>
        public static string user_created_successfully {
            get {
                return ResourceManager.GetString("user_created_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not exist.
        /// </summary>
        public static string user_not_exist {
            get {
                return ResourceManager.GetString("user_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        public static string waiting {
            get {
                return ResourceManager.GetString("waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already used the hold option.
        /// </summary>
        public static string you_have_already_used_the_hold_option {
            get {
                return ResourceManager.GetString("you_have_already_used_the_hold_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to be at the location to access the services.
        /// </summary>
        public static string you_need_to_be_at_the_location_to_access_the_services {
            get {
                return ResourceManager.GetString("you_need_to_be_at_the_location_to_access_the_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email.
        /// </summary>
        public static string your_email {
            get {
                return ResourceManager.GetString("your_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Ticket is now on hold.
        /// </summary>
        public static string your_ticket_is_now_on_hold {
            get {
                return ResourceManager.GetString("your_ticket_is_now_on_hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ticket is under process.
        /// </summary>
        public static string your_ticket_is_under_process {
            get {
                return ResourceManager.GetString("your_ticket_is_under_process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Ticket Resumed.
        /// </summary>
        public static string your_ticket_resumed {
            get {
                return ResourceManager.GetString("your_ticket_resumed", resourceCulture);
            }
        }
    }
}
